[project]
name = "networkmotif"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "networkx>=3.2.1",
    "streamlit>=1.39.0",
]
